# Generated by Django 2.1.7 on 2019-03-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190317_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default='<jamming-date>', verbose_name='Date'),
        ),
    ]
